name = "Gaussquad"
uuid = "ff7d88ef-8a7b-4be5-9ac4-5da6dffbeadd"
authors = ["kjy <kangjiayin@mail.nankai.edu.cn>"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
